repository:
    private: true
    has_issues: true
    has_wiki: false
    has_downloads: true
    default_branch: main
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: false


branches:
    - name: main
      protection:
          required_pull_request_reviews:
              required_approving_review_count: 1
              dismiss_stale_reviews: true
              require_code_owner_reviews: true
          # Required. Require status checks to pass before merging. Set to null to disable
          required_status_checks:
              # Required. Require branches to be up to date before merging.
              strict: true
              # Required. The list of status checks to require in order to merge into this branch
              contexts: []
          # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
          enforce_admins: false
          # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
          restrictions:
              apps: []
              users: []
              teams: []