name: 'ci'
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16"]
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        if: matrix.node-version == 16
        uses: actions/cache@v2
        with:
          path: |
            dist
            README.md
          key: ${{ github.run_number }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Check format and lint
        run: yarn run format-check && yarn lint

      - name: Run tests
        run: yarn test

      - name: Build and package
        run: yarn build && yarn run package

      - name: Update docs
        uses: npalm/action-docs-action@v1.3.0

      - name: Get token
        uses: './'
        id: app-token
        with:
          appId: ${{ secrets.APP_ID }}
          appPrivateKeyBase64: ${{ secrets.APP_PRIVATE_KEY_BASE64 }}
          appInstallationType: repo
          appInstallationValue: ${{ github.repository }}

      - name: Dry run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: yarn release -d --repositoryUrl https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git -d

  dist:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            dist
            README.md
          key: ${{ github.run_number }}

      - name: Update README in the repository
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "chore(ci): Updating readme docs."
          file_pattern: README.md

      - name: Update dist in the repository
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "chore(ci): Updating dist"
          file_pattern: dist/*.js